# Generated by Django 4.2.4 on 2023-10-22 13:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="organizingcommitteeTeam",
            new_name="committeeTeam",
        ),
    ]
