# Generated by Django 4.2.4 on 2024-07-04 17:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0004_photo"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="headTeam",
            new_name="head_HS",
        ),
    ]
