# Generated by Django 4.2.4 on 2024-07-04 18:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0006_rename_committeeteam_committee_hs"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="committee_HS",
            new_name="committee",
        ),
        migrations.RenameModel(
            old_name="head_HS",
            new_name="head",
        ),
        migrations.RenameModel(
            old_name="memberTeam",
            new_name="member",
        ),
    ]
