# Generated by Django 4.2.4 on 2024-07-04 18:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0007_rename_committee_hs_committee_rename_head_hs_head_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="advisorTeam",
            new_name="advisor",
        ),
    ]
