# Generated by Django 4.2.4 on 2024-07-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0009_committee_team_type_head_team_type_member_team_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="aboutUsPhotos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image1", models.ImageField(upload_to="about_us_photos/")),
                ("image2", models.ImageField(upload_to="about_us_photos/")),
                ("image3", models.ImageField(upload_to="about_us_photos/")),
            ],
        ),
    ]
