# Generated by Django 4.2.4 on 2024-07-04 19:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0010_aboutusphotos"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="aboutUsPhotos",
            new_name="aboutUsPhoto",
        ),
    ]
