# Generated by Django 5.0.6 on 2024-07-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_rename_aboutusphotos_aboutusphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=100)),
                ('activity', models.TextField()),
                ('date', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='activity_name',
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='date',
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='location',
        ),
        migrations.AddField(
            model_name='timeline',
            name='end_year',
            field=models.CharField(default='2025', max_length=4),
        ),
        migrations.AddField(
            model_name='timeline',
            name='start_year',
            field=models.CharField(default='2024', max_length=4),
        ),
        migrations.AddField(
            model_name='timeline',
            name='activities',
            field=models.ManyToManyField(blank=True, to='website.activity'),
        ),
    ]
