# Generated by Django 4.2.4 on 2024-09-05 19:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0018_alter_photo_activity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="advisor",
            name="about",
        ),
        migrations.RemoveField(
            model_name="committee",
            name="about",
        ),
        migrations.RemoveField(
            model_name="head",
            name="about",
        ),
        migrations.RemoveField(
            model_name="member",
            name="about",
        ),
    ]
